"""
Django settings for picture_game project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

if 'test' in sys.argv:
    ENVIRONMENT = "test"
else:
    ENVIRONMENT = "dev"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

SECRET_KEY = "change_this_on_a_real_server"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

TESTING_URL = 'localhost'

ALLOWED_HOSTS = [
    TESTING_URL
]

CSRF_TRUSTED_ORIGINS = [
    f'https://{ TESTING_URL }'
]

CHANNEL_LAYERS = {
    'default': {
        # Method 1: Via redis lab
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [
                'redis://localhost:6379'
            ],
        },

        # Method 2: Via local Redis
        # 'BACKEND': 'channels_redis.core.RedisChannelLayer',
        # 'CONFIG': {
        #      "hosts": [('127.0.0.1', 6379)],
        # },

        # Method 3: Via In-memory channel layer
        # this method.
        # "BACKEND": "channels.layers.InMemoryChannelLayer"
    },
}


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("SQL_DATABASE", BASE_DIR / "db.sqlite3"),
        "USER": os.environ.get("SQL_USER", "user"),
        "PASSWORD": os.environ.get("SQL_PASSWORD", "password"),
        "HOST": os.environ.get("SQL_HOST", "localhost"),
        "PORT": os.environ.get("SQL_PORT", "5432"),
    }
}

REDIS_URL = 'redis://localhost:6379/0'

MEDIA_URL = "media/"
MEDIA_ROOT = "media/"

INTERNAL_IPS = [
    "127.0.0.1",
]

CDN_BASE_URL = "/" + MEDIA_ROOT
