# Generated by Django 4.1.2 on 2022-11-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(default="", max_length=50)),
                ("file", models.FileField(upload_to="images")),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
