# Generated by Django 4.1.2 on 2022-11-29 23:01

import hashlib
import os

from django.conf import settings
from django.core.files.images import ImageFile
from django.db import migrations

IMAGE_PATH = "images/fixtures/"


def initialize_images(apps, _):
    if settings.ENVIRONMENT == 'test':
        return

    Image = apps.get_model('images', 'Image')

    for img in os.listdir(IMAGE_PATH):
        caption = img[0:-4].replace('_', ' ').upper()
        with open(os.path.join(IMAGE_PATH, img), 'rb') as file:
            Image.objects.create(
                caption=caption,
                file=ImageFile(file,
                               name=hashlib.md5(caption.encode()).hexdigest()
                               + img[-4:]))


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(initialize_images)
    ]
