# Generated by Django 4.1.2 on 2022-10-19 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(default="", max_length=20)),
                ("anonymous_user_id", models.UUIDField(default=uuid.uuid4)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ST", "Starting"),
                            ("R1", "Guessing Round One"),
                            ("R2", "Guessing Round Two"),
                            ("R3", "Guessing Round Three"),
                            ("R4", "Guessing Round Four"),
                            ("R5", "Guessing Round Five"),
                            ("V1", "Voting Round One"),
                            ("V2", "Voting Round Two"),
                            ("V3", "Voting Round Three"),
                            ("V4", "Voting Round Four"),
                            ("V5", "Voting Round Five"),
                            ("CM", "Complete"),
                            ("AB", "Abandoned"),
                        ],
                        default="ST",
                        max_length=2,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.player"
                    ),
                ),
            ],
        ),
    ]
