# Generated by Django 4.1.2 on 2022-10-21 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="players",
            field=models.ManyToManyField(
                related_name="played_games", to="games.player"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_games",
                to="games.player",
            ),
        ),
    ]
