# Generated by Django 4.1.2 on 2022-11-10 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_round_guess"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("ST", "Starting"),
                    ("R1", "Guessing Round One"),
                    ("R2", "Guessing Round Two"),
                    ("R3", "Guessing Round Three"),
                    ("R4", "Guessing Round Four"),
                    ("R5", "Guessing Round Five"),
                    ("V1", "Voting Round One"),
                    ("V2", "Voting Round Two"),
                    ("V3", "Voting Round Three"),
                    ("V4", "Voting Round Four"),
                    ("V5", "Voting Round Five"),
                    ("S1", "Show Score Round One"),
                    ("S2", "Show Score Round Two"),
                    ("S3", "Show Score Round Three"),
                    ("S4", "Show Score Round Four"),
                    ("S5", "Show Score Round Five"),
                    ("CM", "Complete"),
                    ("AB", "Abandoned"),
                ],
                default="ST",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="guess",
            name="player",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guesses",
                to="games.player",
            ),
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guess",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="games.guess",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.player"
                    ),
                ),
            ],
        ),
    ]
