# Generated by Django 4.1.2 on 2022-11-25 21:56

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_alter_game_status_alter_guess_player_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="created",
            field=models.DateTimeField(auto_now_add=True,
                                       default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="next_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
