# Generated by Django 4.1.2 on 2022-11-26 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_game_created_game_next_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
