# Generated by Django 4.1.2 on 2023-10-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_game_scoring_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
